title: Deep Learning Specialization
email: lionel.brol@gmail.com.com
description: >- # this means to ignore newlines until "baseurl:"
  Deep Learning Specialization
baseurl: "/deep-learning-specialization-courser" # the subpath of your site, e.g. /blog
url: "https://mauvaisetroupe.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mauvaisetroupe
github_username:  mauvaisetroupe

# Build settings
theme: just-the-docs

math: mathjax


#logo: "assets/images/logo-ea-design.svg"
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
aux_links_new_tab: true
